# https://docs.openfaas.com/reference/cicd/gitlab/

variables:
  CONTAINER_TAG_IMAGE: $CI_REGISTRY_IMAGE:build-$CI_BUILD_REF_NAME
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:build-$CI_PIPELINE_ID
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://localhost:2375/


services:
- docker:18.09.7-dind

before_script:
- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

stages:
  - build
  - deploy

# Cache the templates and build-context to speed things up
cache:
  key: ${CI_COMMIT_REF_SLUG} # i.e. master
  paths:
  - ./faas-cli
  - ./template

# Build the whole stack using only the faas-cli
build:
  script:
  - docker build -f Dockerfile -t $CONTAINER_IMAGE .
  - docker push $CONTAINER_IMAGE
  - docker tag $CONTAINER_IMAGE $CONTAINER_TAG_IMAGE && docker push $CONTAINER_TAG_IMAGE
  only:
    - main
