# https://docs.openfaas.com/reference/cicd/gitlab/

variables:
  #CONTAINER_TAG_IMAGE: $CI_REGISTRY_IMAGE:build-$CI_BUILD_REF_NAME
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:build-$CI_PIPELINE_ID
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://localhost:2375/


services:
- docker:18.09.7-dind

before_script:
- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

stages:
  - build

# Build the whole stack using only the faas-cli
build:
  stage: build
  image: docker
  script:
  - docker build -f Dockerfile -t $CONTAINER_IMAGE .
  - docker push $CONTAINER_IMAGE
  - docker tag $CONTAINER_IMAGE $CONTAINER_RELEASE_IMAGE && docker push $CONTAINER_RELEASE_IMAGE
  only:
    - main
    - feature/141-link-rust-and-python # temporary for testing CI
