# Safety Security and License Configuration file
security: # configuration for the `safety check` command
    ignore-vulnerabilities: 
        51457: 
            reason: Only a test dependency 
        70612:
            reason: Doesn't affect us due to no templates being used. Owners won't be updating it.
security-updates: # configuration for the `safety check --apply-security-updates` command
    auto-security-updates-limit:
        # A list of allowed values: major, minor, patch
        - minor
