version: "3.9"  # optional since v1.27.0
services:
  category:
    build:
      context: .
    network_mode: host
    volumes:
      - ./taxonomy.json:/app/taxonomy.json
      - ./test_data:/app/test_data
      - ./cache:/app/cache
      - ./.env:/app/.env
