---

platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker.io/library/docker
    tag: latest

inputs:
  - name: dp-nlp-category-api

outputs:
  - name: build

caches:
  - path: dp-nlp-category-api/.poetry/
  - path: dp-nlp-category-api/.venv/
  
params:
  USERNAME: default_username
  PASSWORD: default_password

run:
  path: bash
  args:
    - -exc
    - |
      pwd
      ls
      ls dp-nlp-category-api
      ls dp-nlp-category-api/ci
      ls dp-nlp-category-api/ci/scripts
      bash dp-nlp-category-api/ci/scripts/build.sh $USERNAME $PASSWORD
