---

platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker.io/library/docker
    tag: latest

inputs:
  - name: dp-nlp-category-api

outputs:
  - name: build

caches:
  - path: dp-nlp-category-api/.poetry/
  - path: dp-nlp-category-api/.venv/
  
params:
  USERNAME: ((username))
  PASSWORD: ((password))

run:
  path: dp-nlp-category-api/ci/scripts/build.sh $USERNAME $PASSWORD
