---

platform: linux

image_resource:
  type: registry-image
  source:
    repository: concourse/oci-build-task

inputs:
- name: dp-nlp-category-api

outputs:
- name: image

caches:
  - path: dp-nlp-category-api/.poetry/
  - path: dp-nlp-category-api/.venv/
  
params:
  CONTEXT: dp-nlp-category-api/
  DOCKERFILE: dp-nlp-category-api/Dockerfile.in

run:
  path: build