---

platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker.io/library/docker:dind
    tag: latest

inputs:
  - name: dp-nlp-category-api

outputs:
  - name: build

caches:
  - path: dp-nlp-category-api/.poetry/
  - path: dp-nlp-category-api/.venv/
  
params:
  USERNAME: default_username
  PASSWORD: default_password

run:
  path: sh
  args:
    - -exc
    - |
      apk add bash
      apk add make
      apk add m4
      chmod +x dp-nlp-category-api/ci/scripts/build.sh
      ./dp-nlp-category-api/ci/scripts/build.sh $USERNAME $PASSWORD
