---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: python
    tag: 3.9.16

inputs:
  - name: dp-nlp-category-api

outputs:
  - name: build

caches:
  - path: dp-nlp-category-api/.poetry/
  - path: dp-nlp-category-api/.venv/
  
run:
  path: dp-nlp-category-api/ci/scripts/build.sh
